import React, { useState, useRef, useEffect } from 'react';
import jsPDF from 'jspdf';
import type { WikiMetadata, AsciiArtData } from '../services/providers/types';
import { exportAsMarkdown, exportAsJson, exportAsText, downloadFile } from '../lib/export';

interface ExportMenuProps {
  topic: string;
  content: string;
  metadata: WikiMetadata | null;
  asciiArt: AsciiArtData | null;
  language: string;
}

const ExportMenu: React.FC<ExportMenuProps> = ({ topic, content, metadata, asciiArt, language }) => {
  const [isOpen, setIsOpen] = useState(false);
  const menuRef = useRef<HTMLDivElement>(null);

  const slugifiedTopic = topic.toLowerCase().replace(/\s+/g, '-');

  // Close dropdown when clicking outside
  useEffect(() => {
    const handleClickOutside = (e: MouseEvent) => {
      if (menuRef.current && !menuRef.current.contains(e.target as Node)) {
        setIsOpen(false);
      }
    };

    if (isOpen) {
      document.addEventListener('mousedown', handleClickOutside);
    }

    return () => {
      document.removeEventListener('mousedown', handleClickOutside);
    };
  }, [isOpen]);

  const handleExportPdf = () => {
    const doc = new jsPDF({
      orientation: 'portrait',
      unit: 'mm',
      format: 'a4',
    });

    const pageWidth = doc.internal.pageSize.getWidth();
    const pageHeight = doc.internal.pageSize.getHeight();
    const margin = 20;
    const maxWidth = pageWidth - 2 * margin;
    let yPosition = margin;

    // Title
    doc.setFontSize(24);
    doc.setTextColor(0, 0, 0);
    doc.text('Wiki Bite', margin, yPosition);
    yPosition += 15;

    // Topic
    doc.setFontSize(18);
    doc.text(topic, margin, yPosition);
    yPosition += 12;

    // ASCII Art
    if (asciiArt && asciiArt.art) {
      doc.setFontSize(6);
      doc.setFont('courier');
      const artLines = asciiArt.art.split('\n');
      artLines.forEach((line) => {
        if (yPosition > pageHeight - margin) {
          doc.addPage();
          yPosition = margin;
        }
        doc.text(line, margin, yPosition);
        yPosition += 3;
      });
      yPosition += 8;
      doc.setFont('helvetica');
    }

    // Separator
    doc.setLineWidth(0.5);
    doc.setDrawColor(200, 200, 200);
    doc.line(margin, yPosition, pageWidth - margin, yPosition);
    yPosition += 8;

    // Content
    doc.setFontSize(11);
    doc.setTextColor(40, 40, 40);
    const contentLines = doc.splitTextToSize(content, maxWidth);
    contentLines.forEach((line: string) => {
      if (yPosition > pageHeight - margin) {
        doc.addPage();
        yPosition = margin;
      }
      doc.text(line, margin, yPosition);
      yPosition += 6;
    });

    // Key Facts
    if (metadata && metadata.keyFacts && metadata.keyFacts.length > 0) {
      yPosition += 10;
      if (yPosition > pageHeight - margin - 20) {
        doc.addPage();
        yPosition = margin;
      }
      doc.setFontSize(14);
      doc.setTextColor(0, 0, 0);
      doc.text('Key Facts', margin, yPosition);
      yPosition += 8;
      doc.setFontSize(10);
      doc.setTextColor(60, 60, 60);
      metadata.keyFacts.forEach((fact) => {
        const factLines = doc.splitTextToSize(`\u2022 ${fact}`, maxWidth);
        factLines.forEach((line: string) => {
          if (yPosition > pageHeight - margin) {
            doc.addPage();
            yPosition = margin;
          }
          doc.text(line, margin, yPosition);
          yPosition += 5;
        });
        yPosition += 2;
      });
    }

    // Related Topics
    if (metadata && metadata.relatedTopics && metadata.relatedTopics.length > 0) {
      yPosition += 8;
      if (yPosition > pageHeight - margin - 20) {
        doc.addPage();
        yPosition = margin;
      }
      doc.setFontSize(14);
      doc.setTextColor(0, 0, 0);
      doc.text('Related Topics', margin, yPosition);
      yPosition += 8;
      doc.setFontSize(10);
      doc.setTextColor(60, 60, 60);
      const topics = metadata.relatedTopics.join(' \u2022 ');
      const topicLines = doc.splitTextToSize(topics, maxWidth);
      topicLines.forEach((line: string) => {
        if (yPosition > pageHeight - margin) {
          doc.addPage();
          yPosition = margin;
        }
        doc.text(line, margin, yPosition);
        yPosition += 5;
      });
    }

    // Footer
    const footerY = pageHeight - 10;
    doc.setFontSize(8);
    doc.setTextColor(150, 150, 150);
    doc.text('Generated by Wiki Bite | biteskill.com', margin, footerY);

    doc.save(`${slugifiedTopic}-wikibite.pdf`);
    setIsOpen(false);
  };

  const handleExportMarkdown = () => {
    const md = exportAsMarkdown(topic, content, metadata, asciiArt);
    downloadFile(md, `${slugifiedTopic}-wikibite.md`, 'text/markdown');
    setIsOpen(false);
  };

  const handleExportJson = () => {
    const json = exportAsJson(topic, language, content, metadata, asciiArt);
    downloadFile(json, `${slugifiedTopic}-wikibite.json`, 'application/json');
    setIsOpen(false);
  };

  const handleExportText = () => {
    const txt = exportAsText(topic, content, metadata);
    downloadFile(txt, `${slugifiedTopic}-wikibite.txt`, 'text/plain');
    setIsOpen(false);
  };

  const menuItemProps = (onClick: () => void) => ({
    onClick,
    style: styles.menuItem,
    onMouseEnter: (e: React.MouseEvent<HTMLButtonElement>) => {
      e.currentTarget.style.background = 'var(--border-color)';
    },
    onMouseLeave: (e: React.MouseEvent<HTMLButtonElement>) => {
      e.currentTarget.style.background = 'transparent';
    },
    role: 'menuitem' as const,
  });

  return (
    <div ref={menuRef} style={styles.container}>
      <button
        onClick={() => setIsOpen(!isOpen)}
        style={styles.button}
        onMouseEnter={(e) => (e.currentTarget.style.opacity = '0.9')}
        onMouseLeave={(e) => (e.currentTarget.style.opacity = '1')}
        aria-label="Export options"
        aria-expanded={isOpen}
        aria-haspopup="true"
      >
        <span>Export</span>
        <span style={{ fontSize: '0.7rem', marginLeft: '0.3rem' }}>{isOpen ? '\u25B2' : '\u25BC'}</span>
      </button>

      {isOpen && (
        <div style={styles.dropdown} role="menu">
          <button {...menuItemProps(handleExportPdf)}>PDF (.pdf)</button>
          <button {...menuItemProps(handleExportMarkdown)}>Markdown (.md)</button>
          <button {...menuItemProps(handleExportJson)}>JSON (.json)</button>
          <button {...menuItemProps(handleExportText)}>Plain Text (.txt)</button>
        </div>
      )}
    </div>
  );
};

const styles: Record<string, React.CSSProperties> = {
  container: {
    position: 'relative',
    display: 'inline-block',
  },
  button: {
    background: 'var(--accent-color)',
    color: '#fff',
    border: 'none',
    padding: '0.6rem 1.2rem',
    borderRadius: '4px',
    cursor: 'pointer',
    fontSize: '0.9rem',
    display: 'flex',
    alignItems: 'center',
    gap: '0.5rem',
    transition: 'opacity 0.2s',
  },
  dropdown: {
    position: 'absolute',
    top: '100%',
    left: 0,
    marginTop: '0.25rem',
    background: 'var(--bg-color)',
    border: '1px solid var(--border-color)',
    borderRadius: '4px',
    minWidth: '180px',
    zIndex: 100,
    boxShadow: '0 4px 12px rgba(0, 0, 0, 0.15)',
    overflow: 'hidden',
  },
  menuItem: {
    display: 'block',
    width: '100%',
    padding: '0.6rem 1rem',
    border: 'none',
    background: 'transparent',
    color: 'var(--text-color)',
    fontSize: '0.85rem',
    cursor: 'pointer',
    textAlign: 'left' as const,
    transition: 'background 0.15s',
  },
};

export default ExportMenu;
