import React from 'react';
import jsPDF from 'jspdf';
import type { WikiMetadata, AsciiArtData } from '../services/providers/types';

interface PdfExportProps {
    topic: string;
    content: string;
    metadata: WikiMetadata | null;
    asciiArt: AsciiArtData | null;
    language: string;
}

const PdfExport: React.FC<PdfExportProps> = ({ topic, content, metadata, asciiArt, language }) => {
    const generatePDF = () => {
        const doc = new jsPDF({
            orientation: 'portrait',
            unit: 'mm',
            format: 'a4',
        });

        const pageWidth = doc.internal.pageSize.getWidth();
        const pageHeight = doc.internal.pageSize.getHeight();
        const margin = 20;
        const maxWidth = pageWidth - 2 * margin;
        let yPosition = margin;

        // Title
        doc.setFontSize(24);
        doc.setTextColor(0, 0, 0);
        doc.text('Wiki Bite', margin, yPosition);
        yPosition += 15;

        // Topic
        doc.setFontSize(18);
        doc.text(topic, margin, yPosition);
        yPosition += 12;

        // ASCII Art (if available)
        if (asciiArt && asciiArt.art) {
            doc.setFontSize(6);
            doc.setFont('courier');
            const artLines = asciiArt.art.split('\n');
            artLines.forEach((line) => {
                if (yPosition > pageHeight - margin) {
                    doc.addPage();
                    yPosition = margin;
                }
                doc.text(line, margin, yPosition);
                yPosition += 3;
            });
            yPosition += 8;
            doc.setFont('helvetica');
        }

        // Separator line
        doc.setLineWidth(0.5);
        doc.setDrawColor(200, 200, 200);
        doc.line(margin, yPosition, pageWidth - margin, yPosition);
        yPosition += 8;

        // Content
        doc.setFontSize(11);
        doc.setTextColor(40, 40, 40);
        const contentLines = doc.splitTextToSize(content, maxWidth);
        contentLines.forEach((line: string) => {
            if (yPosition > pageHeight - margin) {
                doc.addPage();
                yPosition = margin;
            }
            doc.text(line, margin, yPosition);
            yPosition += 6;
        });

        // Key Facts
        if (metadata && metadata.keyFacts && metadata.keyFacts.length > 0) {
            yPosition += 10;
            if (yPosition > pageHeight - margin - 20) {
                doc.addPage();
                yPosition = margin;
            }

            doc.setFontSize(14);
            doc.setTextColor(0, 0, 0);
            doc.text('Key Facts', margin, yPosition);
            yPosition += 8;

            doc.setFontSize(10);
            doc.setTextColor(60, 60, 60);
            metadata.keyFacts.forEach((fact) => {
                const factLines = doc.splitTextToSize(`• ${fact}`, maxWidth);
                factLines.forEach((line: string) => {
                    if (yPosition > pageHeight - margin) {
                        doc.addPage();
                        yPosition = margin;
                    }
                    doc.text(line, margin, yPosition);
                    yPosition += 5;
                });
                yPosition += 2;
            });
        }

        // Related Topics
        if (metadata && metadata.relatedTopics && metadata.relatedTopics.length > 0) {
            yPosition += 8;
            if (yPosition > pageHeight - margin - 20) {
                doc.addPage();
                yPosition = margin;
            }

            doc.setFontSize(14);
            doc.setTextColor(0, 0, 0);
            doc.text('Related Topics', margin, yPosition);
            yPosition += 8;

            doc.setFontSize(10);
            doc.setTextColor(60, 60, 60);
            const topics = metadata.relatedTopics.join(' • ');
            const topicLines = doc.splitTextToSize(topics, maxWidth);
            topicLines.forEach((line: string) => {
                if (yPosition > pageHeight - margin) {
                    doc.addPage();
                    yPosition = margin;
                }
                doc.text(line, margin, yPosition);
                yPosition += 5;
            });
        }

        // Footer
        const footerY = pageHeight - 10;
        doc.setFontSize(8);
        doc.setTextColor(150, 150, 150);
        doc.text('Generated by Wiki Bite | biteskill.com', margin, footerY);

        // Save
        const filename = `${topic.toLowerCase().replace(/\s+/g, '-')}-wikibite.pdf`;
        doc.save(filename);
    };

    return (
        <button
            onClick={generatePDF}
            style={{
                background: 'var(--accent-color)',
                color: '#fff',
                border: 'none',
                padding: '0.6rem 1.2rem',
                borderRadius: '4px',
                cursor: 'pointer',
                fontSize: '0.9rem',
                display: 'flex',
                alignItems: 'center',
                gap: '0.5rem',
                transition: 'opacity 0.2s',
            }}
            onMouseEnter={e => e.currentTarget.style.opacity = '0.9'}
            onMouseLeave={e => e.currentTarget.style.opacity = '1'}
            aria-label="Download as PDF"
        >
            <span>📄</span>
            <span>Export PDF</span>
        </button>
    );
};

export default PdfExport;
