import { WikiMetadata, AsciiArtData } from '../services/geminiService';

/**
 * Exports wiki content as a Markdown string.
 */
export function exportAsMarkdown(
  topic: string,
  content: string,
  metadata: WikiMetadata | null,
  asciiArt: AsciiArtData | null
): string {
  const parts: string[] = [];

  parts.push(`# ${topic}\n`);

  if (asciiArt?.art) {
    parts.push('```');
    parts.push(asciiArt.art);
    parts.push('```\n');
  }

  parts.push(content);
  parts.push('');

  if (metadata?.keyFacts && metadata.keyFacts.length > 0) {
    parts.push('## Key Facts\n');
    metadata.keyFacts.forEach((fact) => {
      parts.push(`- ${fact}`);
    });
    parts.push('');
  }

  if (metadata?.relatedTopics && metadata.relatedTopics.length > 0) {
    parts.push('## Related Topics\n');
    parts.push(metadata.relatedTopics.join(' | '));
    parts.push('');
  }

  parts.push('---');
  parts.push('*Generated by Wiki Bite | biteskill.com*');

  return parts.join('\n');
}

/**
 * Exports wiki content as a JSON string.
 */
export function exportAsJson(
  topic: string,
  lang: string,
  content: string,
  metadata: WikiMetadata | null,
  asciiArt: AsciiArtData | null
): string {
  const data = {
    topic,
    language: lang,
    content,
    asciiArt: asciiArt?.art ?? null,
    keyFacts: metadata?.keyFacts ?? [],
    relatedTopics: metadata?.relatedTopics ?? [],
    exportedAt: new Date().toISOString(),
    source: 'Wiki Bite | biteskill.com',
  };

  return JSON.stringify(data, null, 2);
}

/**
 * Exports wiki content as a plain text string.
 */
export function exportAsText(
  topic: string,
  content: string,
  metadata: WikiMetadata | null
): string {
  const parts: string[] = [];

  parts.push(topic.toUpperCase());
  parts.push('='.repeat(topic.length));
  parts.push('');
  parts.push(content);
  parts.push('');

  if (metadata?.keyFacts && metadata.keyFacts.length > 0) {
    parts.push('KEY FACTS');
    parts.push('---------');
    metadata.keyFacts.forEach((fact) => {
      parts.push(`* ${fact}`);
    });
    parts.push('');
  }

  if (metadata?.relatedTopics && metadata.relatedTopics.length > 0) {
    parts.push('RELATED TOPICS');
    parts.push('--------------');
    parts.push(metadata.relatedTopics.join(', '));
    parts.push('');
  }

  parts.push('Generated by Wiki Bite | biteskill.com');

  return parts.join('\n');
}

/**
 * Triggers a file download in the browser.
 */
export function downloadFile(
  content: string,
  filename: string,
  mimeType: string
): void {
  const blob = new Blob([content], { type: mimeType });
  const url = URL.createObjectURL(blob);
  const link = document.createElement('a');
  link.href = url;
  link.download = filename;
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
  URL.revokeObjectURL(url);
}
